---
title: "Municipis, comarques i regions"
engine: knitr
execute:
  echo: false
---



```{r biblioteques}
suppressPackageStartupMessages(library(monitorOSM, quietly = TRUE))

# TODO: Sys.setlocale("LC_TIME", "ca_AD.UTF-8") # requereix configurar locale a gh action https://github.com/actions/runner-images/issues/762
```

Última actualització: `r format(Sys.time(), "%a %d %b %Y - %X")`

## Països Catalans

[BD de referència](https://github.com/OSM-Catalan/monitorOSM/blob/main/data-raw/PPCC.tsv)

```{r ppcc}
canvis_ppcc <- comprova_canvis_osm(PPCC, centre = TRUE)
canvis_html(canvis_ppcc)
```

`r if(nrow(canvis_ppcc$comparison_df) > 0){"### Conjunt de canvis"}`

```{r ppcc_canvis, results='asis'}
versio_canvis_ppcc <- cerca_versio_canvis(canvis_ppcc)
versio_canvis_html(versio_canvis_ppcc)
```

## Territoris

[BD de referència](https://github.com/OSM-Catalan/monitorOSM/blob/main/data-raw/territoris.tsv)

```{r territoris}
canvis_territoris <- comprova_canvis_osm(territoris[, setdiff(names(territoris), "regio")], centre = TRUE)
canvis_html(canvis_territoris)
```

`r if(nrow(canvis_territoris$comparison_df) > 0){"### Conjunts de canvis"}`

```{r territoris_canvis, results='asis'}
versio_canvis_territoris <- cerca_versio_canvis(canvis_territoris)
versio_canvis_html(versio_canvis_territoris)
```

## Comarques

[BD de referència](https://github.com/OSM-Catalan/monitorOSM/blob/main/data-raw/comarques.tsv)

```{r comarques}
canvis_comarques <- comprova_canvis_osm(comarques[, setdiff(names(comarques), "regio")], centre = TRUE)
canvis_html(canvis_comarques)
```

`r if(nrow(canvis_comarques$comparison_df) > 0){"### Conjunts de canvis"}`

```{r comarques_canvis, results='asis'}
versio_canvis_comarques <- cerca_versio_canvis(canvis_comarques)
versio_canvis_html(versio_canvis_comarques)
```

## Municipis

[BD de referència](https://github.com/OSM-Catalan/monitorOSM/blob/main/data-raw/municipis.tsv)

```{r municipis}
canvis_municipis <- comprova_canvis_osm(municipis[, setdiff(names(municipis), c("regio", "comarca"))], centre = TRUE)
canvis_html(canvis_municipis)
```

`r if(nrow(canvis_municipis$comparison_df) > 0){"### Conjunts de canvis"}`

```{r municipis_canvis, results='asis'}
versio_canvis_municipis <- cerca_versio_canvis(canvis_municipis)
versio_canvis_html(versio_canvis_municipis)
```


```{r telegram}
hi_ha_canvis <- sapply(list(canvis_ppcc, canvis_territoris, canvis_comarques, canvis_municipis), function(x) {
  nrow(x$comparison_df) > 0
})

if (any(hi_ha_canvis) &&
  Sys.getenv("GITHUB_EVENT_NAME") == "schedule" &&
  # format(Sys.Date(), format = "%u") %in% "5" &&  # Només els divendres
  Sys.getenv("GITHUB_WORKFLOW") == "Render and Publish"
) {
  m <- missatge_telegram(missatge = "Hi ha canvis a [*limits*](https://osm-catalan.github.io/monitorOSM/web/limits.html).")
}
```
