---
title: "Localitats"
engine: knitr
execute:
  echo: false
---



```{r biblioteques}
suppressPackageStartupMessages(library(monitorOSM, quietly = TRUE))
```

Última actualització: `r format(Sys.time(), "%a %d %b %Y - %X")`

## Localitats que fan d'`admin_centre` de relacions de municipis

[BD de referència](https://github.com/OSM-Catalan/monitorOSM/blob/main/data-raw/loc_admin_centre_municipis.tsv)

```{r admin_centre municipis}
canvis_loc_capital_municipis <- comprova_canvis_osm(
  loc_admin_centre_municipis[, setdiff(names(loc_admin_centre_municipis), c("regio", "comarca", "municipi"))],
  centre = TRUE
)
canvis_html(canvis_loc_capital_municipis)
```

`r if(nrow(canvis_loc_capital_municipis$comparison_df) > 0){"### Conjunts de canvis"}`

```{r localitats_admin_centre_municipis_canvis, results='asis'}
versio_canvis_loc_capital <- cerca_versio_canvis(canvis_loc_capital_municipis)
versio_canvis_html(versio_canvis_loc_capital)
```

## Localitats amb alguna etiqueta `ref:*` de l'administració

S'ometen objectes que ja són presents en altres taules de localitats.

[BD de referència](https://github.com/OSM-Catalan/monitorOSM/blob/main/data-raw/loc_ref.tsv)

```{r ref administració}
canvis_loc_ref <- comprova_canvis_osm(
  loc_ref[, setdiff(names(loc_ref), c("regio", "comarca", "municipi"))],
  centre = TRUE
)
canvis_html(canvis_loc_ref)
```

`r if(nrow(canvis_loc_ref$comparison_df) > 0){"### Conjunts de canvis"}`

```{r localitats_ref_canvis, results='asis'}
versio_canvis_loc_capital <- cerca_versio_canvis(canvis_loc_ref)
versio_canvis_html(versio_canvis_loc_capital)
```


```{r telegram}
n_canvis <- sapply(list(canvis_loc_capital_municipis, canvis_loc_ref), function(x) {
  nrow(x$change_count)
})

if (
  any(n_canvis > 0) &&
    Sys.getenv("GITHUB_EVENT_NAME") == "schedule" &&
    # format(Sys.Date(), format = "%u") %in% "5" &&  # Només els divendres
    Sys.getenv("GITHUB_WORKFLOW") == "Render and Publish"
) {
  missatge <- missatge_resum_informes(
    list(
      admin_centre = canvis_loc_capital_municipis,
      loc_ref = canvis_loc_ref
    ),
    pagina_informe = "localitats"
  )
  m <- envia_missatge_telegram(missatge = missatge)
}
```
